@css = {}

css.elements =
# --------------------------------------------------
# common declarations
# --------------------------------------------------
  "background image url": "background-image: url();"
  "clear both": "clear: both;"
  "cursor default": "cursor: default;"
  "cursor inherit": "cursor: inherit;"
  "cursor pointer": "cursor: pointer;"
  "display block": "display: block;"
  "display inline block": "display: inline-block;"
  "display inline": "display: inline;"
  "display none": "display: none;"
  "display flex": "display: flex;"
  "display table": "display: table;"
  "float left": "float: left;"
  "float none": "float: none;"
  "float right": "float: right;"
  "font style italic": "font-style: italic;"
  "font italic": "font-style: italic;"
  "font style normal": "font-style: normal;"
  "font weight bold": "font-weight: bold;"
  "font bold": "font-weight: bold;"
  "font weight light": "font-weight: light;"
  "font light": "font-weight: light;"
  "font weight normal": "font-weight: normal;"
  "important": "!important"
  "list style circle": "list-style-type: circle;"
  "list style decimal": "list-style-type: decimal;"
  "list style disc": "list-style-type: disc;"
  "list style lower-alpha": "list-style-type: lower-alpha;"
  "list style lower-latin": "list-style-type: lower-latin;"
  "list style lower-roman": "list-style-type: lower-roman;"
  "list style none": "list-style-type: none;"
  "list style square": "list-style-type: square;"
  "list style upper-alpha": "list-style-type: upper-alpha;"
  "list style upper-latin": "list-style-type: upper-latin;"
  "list style upper-roman": "list-style-type: upper-roman;"
  "list style url": "list-style: url();"
  "overflow auto": "overflow: auto;"
  "overflow hidden": "overflow: hidden;"
  "overflow scroll": "overflow: scroll;"
  "overflow visible": "overflow: visible;"
  "position absolute": "position: absolute;"
  "position fixed": "position: fixed;"
  "position relative": "position: relative;"
  "position static": "position: static;"
  "text align center": "text-align: center;"
  "text align left": "text-align: left;"
  "text align right": "text-align: right;"
  "text center": "text-align: center;"
  "text left": "text-align: left;"
  "text right": "text-align: right;"
  "text decoration none": "text-decoration: none;"
  "text decoration underline": "text-decoration: underline;"
  "text uppercase": "text-transform: uppercase;"
  "text transform capitalize": "text-transform: capitalize;"
  "text transform lowercase": "text-transform: lowercase;"
  "text transform none": "text-transform: none;"
  "text transform uppercase": "text-transform: uppercase;"
  "text capitalize": "text-transform: capitalize;"
  "text lowercase": "text-transform: lowercase;"
  "text underline": "text-decoration: underline;"
  "vertical align bottom": "vertical-align: bottom;"
  "vertical align middle": "vertical-align: middle;"
  "vertical align top": "vertical-align: top;"
  "vertical bottom": "vertical-align: bottom;"
  "vertical middle": "vertical-align: middle;"
  "vertical top": "vertical-align: top;"
  "white space normal": "white-space: normal;"
  "white space nowrap": "white-space: nowrap;"
  "white space pre": "white-space: pre;"
  "width auto": "width: auto;"
# --------------------------------------------------
# properties
# --------------------------------------------------
  "additive symbols": "additive-symbols: ;"
  "align content": "align-content: ;"
  "align items": "align-items: ;"
  "align self": "align-self: ;"
  "all": "all: ;"
  "animation": "animation: ;"
  "animation delay": "animation-delay: ;"
  "animation direction": "animation-direction: ;"
  "animation duration": "animation-duration: ;"
  "animation fill mode": "animation-fill-mode: ;"
  "animation iteration count": "animation-iteration-count: ;"
  "animation name": "animation-name: ;"
  "animation play state": "animation-play-state: ;"
  "animation timing function": "animation-timing-function: ;"
  "backface visibility": "backface-visibility: ;"
  "background": "background: ;"
  "background attachment": "background-attachment: ;"
  "background blend mode": "background-blend-mode: ;"
  "background clip": "background-clip: ;"
  "background color": "background-color: ;"
  "background image": "background-image: ;"
  "background origin": "background-origin: ;"
  "background position": "background-position: ;"
  "background repeat": "background-repeat: ;"
  "background size": "background-size: ;"
  "block size": "block-size: ;"
  "border": "border: ;"
  "border block end": "border-block-end: ;"
  "border block end color": "border-block-end-color: ;"
  "border block end style": "border-block-end-style: ;"
  "border block end width": "border-block-end-width: ;"
  "border block start": "border-block-start: ;"
  "border block start color": "border-block-start-color: ;"
  "border block start style": "border-block-start-style: ;"
  "border block start width": "border-block-start-width: ;"
  "border bottom": "border-bottom: ;"
  "border bottom color": "border-bottom-color: ;"
  "border bottom left radius": "border-bottom-left-radius: ;"
  "border bottom right radius": "border-bottom-right-radius: ;"
  "border bottom style": "border-bottom-style: ;"
  "border bottom width": "border-bottom-width: ;"
  "border collapse": "border-collapse: ;"
  "border color": "border-color: ;"
  "border image": "border-image: ;"
  "border image outset": "border-image-outset: ;"
  "border image repeat": "border-image-repeat: ;"
  "border image slice": "border-image-slice: ;"
  "border image source": "border-image-source: ;"
  "border image width": "border-image-width: ;"
  "border inline end": "border-inline-end: ;"
  "border inline end color": "border-inline-end-color: ;"
  "border inline end style": "border-inline-end-style: ;"
  "border inline end width": "border-inline-end-width: ;"
  "border inline start": "border-inline-start: ;"
  "border inline start color": "border-inline-start-color: ;"
  "border inline start style": "border-inline-start-style: ;"
  "border inline start width": "border-inline-start-width: ;"
  "border left": "border-left: ;"
  "border left color": "border-left-color: ;"
  "border left style": "border-left-style: ;"
  "border left width": "border-left-width: ;"
  "border radius": "border-radius: ;"
  "border right": "border-right: ;"
  "border right color": "border-right-color: ;"
  "border right style": "border-right-style: ;"
  "border right width": "border-right-width: ;"
  "border spacing": "border-spacing: ;"
  "border style": "border-style: ;"
  "border top": "border-top: ;"
  "border top color": "border-top-color: ;"
  "border top left radius": "border-top-left-radius: ;"
  "border top right radius": "border-top-right-radius: ;"
  "border top style": "border-top-style: ;"
  "border top width": "border-top-width: ;"
  "border width": "border-width: ;"
  "bottom": "bottom: ;"
  "box decoration break": "box-decoration-break: ;"
  "box shadow": "box-shadow: ;"
  "box sizing": "box-sizing: ;"
  "break after": "break-after: ;"
  "break before": "break-before: ;"
  "break inside": "break-inside: ;"
  "caption side": "caption-side: ;"
  "clear": "clear: ;"
  "clip": "clip: ;"
  "clip path": "clip-path: ;"
  "color": "color: ;"
  "caller": "color: ;"
  "collar": "color: ;"
  "scholar": "color: ;"
  "columns": "columns: ;"
  "column count": "column-count: ;"
  "column fill": "column-fill: ;"
  "column gap": "column-gap: ;"
  "column rule": "column-rule: ;"
  "column rule color": "column-rule-color: ;"
  "column rule style": "column-rule-style: ;"
  "column rule width": "column-rule-width: ;"
  "column span": "column-span: ;"
  "column width": "column-width: ;"
  "content": "content: ;"
  "counter increment": "counter-increment: ;"
  "counter reset": "counter-reset: ;"
  "cursor": "cursor: ;"
  "direction": "direction: ;"
  "display": "display: ;"
  "empty cells": "empty-cells: ;"
  "fallback": "fallback: ;"
  "filter": "filter: ;"
  "flex": "flex: ;"
  "flex basis": "flex-basis: ;"
  "flex direction": "flex-direction: ;"
  "flex flow": "flex-flow: ;"
  "flex grow": "flex-grow: ;"
  "flex shrink": "flex-shrink: ;"
  "flex wrap": "flex-wrap: ;"
  "float": "float: ;"
  "font": "font: ;"
  "font family": "font-family: ;"
  "font feature settings": "font-feature-settings: ;"
  "font kerning": "font-kerning: ;"
  "font language override": "font-language-override: ;"
  "font size": "font-size: ;"
  "font size adjust": "font-size-adjust: ;"
  "font stretch": "font-stretch: ;"
  "font style": "font-style: ;"
  "font synthesis": "font-synthesis: ;"
  "font variant": "font-variant: ;"
  "font variant alternates": "font-variant-alternates: ;"
  "font variant caps": "font-variant-caps: ;"
  "font variant east asian": "font-variant-east-asian: ;"
  "font variant ligatures": "font-variant-ligatures: ;"
  "font variant numeric": "font-variant-numeric: ;"
  "font variant position": "font-variant-position: ;"
  "font weight": "font-weight: ;"
  "grid": "grid: ;"
  "grid area": "grid-area: ;"
  "grid auto columns": "grid-auto-columns: ;"
  "grid auto flow": "grid-auto-flow: ;"
  "grid auto position": "grid-auto-position: ;"
  "grid auto rows": "grid-auto-rows: ;"
  "grid column": "grid-column: ;"
  "grid column start": "grid-column-start: ;"
  "grid column end": "grid-column-end: ;"
  "grid row": "grid-row: ;"
  "grid row start": "grid-row-start: ;"
  "grid row end": "grid-row-end: ;"
  "grid template": "grid-template: ;"
  "grid template areas": "grid-template-areas: ;"
  "grid template rows": "grid-template-rows: ;"
  "grid template columns": "grid-template-columns: ;"
  "height": "height: ;"
  "hyphens": "hyphens: ;"
  "image rendering": "image-rendering: ;"
  "image resolution": "image-resolution: ;"
  "image orientation": "image-orientation: ;"
  "ime mode": "ime-mode: ;"
  "inline size": "inline-size: ;"
  "isolation": "isolation: ;"
  "justify content": "justify-content: ;"
  "left": "left: ;"
  "letter spacing": "letter-spacing: ;"
  "line break": "line-break: ;"
  "line height": "line-height: ;"
  "list style": "list-style: ;"
  "list style image": "list-style-image: ;"
  "list style position": "list-style-position: ;"
  "list style type": "list-style-type: ;"
  "margin": "margin: ;"
  "margin block end": "margin-block-end: ;"
  "margin block start": "margin-block-start: ;"
  "margin bottom": "margin-bottom: ;"
  "margin inline end": "margin-inline-end: ;"
  "margin inline start": "margin-inline-start: ;"
  "margin left": "margin-left: ;"
  "margin right": "margin-right: ;"
  "margin top": "margin-top: ;"
  "marks": "marks: ;"
  "mask": "mask: ;"
  "mask type": "mask-type: ;"
  "max block size": "max-block-size: ;"
  "max height": "max-height: ;"
  "max inline size": "max-inline-size: ;"
  "max width": "max-width: ;"
  "max zoom": "max-zoom: ;"
  "min block size": "min-block-size: ;"
  "min height": "min-height: ;"
  "min height": "min-height: ;"
  "min inline size": "min-inline-size: ;"
  "min width": "min-width: ;"
  "min width": "min-width: ;"
  "min zoom": "min-zoom: ;"
  "mix blend mode": "mix-blend-mode: ;"
  "negative": "negative: ;"
  "object fit": "object-fit: ;"
  "object position": "object-position: ;"
  "offset block end": "offset-block-end: ;"
  "offset block start": "offset-block-start: ;"
  "offset inline end": "offset-inline-end: ;"
  "offset inline start": "offset-inline-start: ;"
  "opacity": "opacity: ;"
  "flex order": "order: ;"
  "orientation": "orientation: ;"
  "orphans": "orphans: ;"
  "outline": "outline: ;"
  "outline color": "outline-color: ;"
  "outline offset": "outline-offset: ;"
  "outline style": "outline-style: ;"
  "outline width": "outline-width: ;"
  "overflow": "overflow: ;"
  "overflow wrap": "overflow-wrap: ;"
  "overflow x": "overflow-x: ;"
  "overflow y": "overflow-y: ;"
  "pad": "pad: ;"
  "padding": "padding: ;"
  "pouting": "padding: ;"
  "padding block end": "padding-block-end: ;"
  "padding block start": "padding-block-start: ;"
  "padding bottom": "padding-bottom: ;"
  "padding inline end": "padding-inline-end: ;"
  "padding inline start": "padding-inline-start: ;"
  "padding left": "padding-left: ;"
  "padding right": "padding-right: ;"
  "padding top": "padding-top: ;"
  "page break after": "page-break-after: ;"
  "page break before": "page-break-before: ;"
  "page break inside": "page-break-inside: ;"
  "perspective": "perspective: ;"
  "perspective origin": "perspective-origin: ;"
  "pointer events": "pointer-events: ;"
  "position": "position: ;"
  "prefix": "prefix: ;"
  "quotes": "quotes: ;"
  "range": "range: ;"
  "resize": "resize: ;"
  "right": "right: ;"
  "ruby align": "ruby-align: ;"
  "ruby merge": "ruby-merge: ;"
  "ruby position": "ruby-position: ;"
  "scroll behavior": "scroll-behavior: ;"
  "scroll snap coordinate": "scroll-snap-coordinate: ;"
  "scroll snap destination": "scroll-snap-destination: ;"
  "scroll snap points x": "scroll-snap-points-x: ;"
  "scroll snap points y": "scroll-snap-points-y: ;"
  "scroll snap type": "scroll-snap-type: ;"
  "scroll snap type x": "scroll-snap-type-x: ;"
  "scroll snap type y": "scroll-snap-type-y: ;"
  "shape image threshold": "shape-image-threshold: ;"
  "shape margin": "shape-margin: ;"
  "shape outside": "shape-outside: ;"
  "speak as": "speak-as: ;"
  "src": "src: ;"
  "source": "src: ;"
  "soars": "src: ;"
  "suffix": "suffix: ;"
  "symbols": "symbols: ;"
  "system": "system: ;"
  "table layout": "table-layout: ;"
  "tab size": "tab-size: ;" # Saying "tablet size" works better
  "text align": "text-align: ;"
  "text align last": "text-align-last: ;"
  "text combine upright": "text-combine-upright: ;"
  "text decoration": "text-decoration: ;"
  "text decoration color": "text-decoration-color: ;"
  "text decoration line": "text-decoration-line: ;"
  "text decoration style": "text-decoration-style: ;"
  "text indent": "text-indent: ;"
  "text orientation": "text-orientation: ;"
  "text overflow": "text-overflow: ;"
  "text rendering": "text-rendering: ;"
  "text shadow": "text-shadow: ;"
  "text transform": "text-transform: ;"
  "text underline position": "text-underline-position: ;"
  "top": "top: ;"
  "touch action": "touch-action: ;"
  "transform": "transform: ;"
  "transform box": "transform-box: ;"
  "transform origin": "transform-origin: ;"
  "transform style": "transform-style: ;"
  "transition": "transition: ;"
  "transition delay": "transition-delay: ;"
  "transition duration": "transition-duration: ;"
  "transition property": "transition-property: ;"
  "transition timing function": "transition-timing-function: ;"
  "turn": "turn: ;"
  "unicode bidi": "unicode-bidi: ;"
  "unicode range": "unicode-range: ;"
  "user zoom": "user-zoom: ;"
  "vertical align": "vertical-align: ;"
  "visibility": "visibility: ;"
  "white space": "white-space: ;"
  "widows": "widows: ;"
  "width": "width: ;"
  "will change": "will-change: ;"
  "word break": "word-break: ;"
  "word spacing": "word-spacing: ;"
  "word wrap": "word-wrap: ;"
  "writing mode": "writing-mode: ;"
  "z index": "z-index: ;"
  "zoom": "zoom: ;"
# --------------------------------------------------
# complex values
# --------------------------------------------------
  "thin border": "1px solid #"
# --------------------------------------------------
# values
# --------------------------------------------------
  # "above": "above"
  # "absolute": "absolute"
  # "alias": "alias"
  "all-petite-caps": "all-petite-caps"
  "all-scroll": "all-scroll"
  "all-small-caps": "all-small-caps"
  # "alphabetic": "alphabetic"
  # "alternate": "alternate"
  "alternate-reverse": "alternate-reverse"
  # "always": "always"
  # "armenian": "armenian"
  # "auto": "auto"
  # "avoid": "avoid"
  "avoid-column": "avoid-column"
  "avoid-page": "avoid-page"
  "avoid-region": "avoid-region"
  # "backwards": "backwards"
  # "balance": "balance"
  # "baseline": "baseline"
  # "below": "below"
  "bidi-override": "bidi-override"
  # "block": "block"
  # "bold": "bold"
  "bolder font": "bolder" # It affects "border" which is more used
  "border-box": "border-box"
  # "both": "both"
  # "bottom": "bottom" # incompatible with the property of the same name
  # "break": "break"
  "break-all": "break-all"
  "break-word": "break-word"
  "capitalize": "capitalize"
  # "cell": "cell"
  # "center": "center"
  # "circle": "circle" # incompatible with the function of the same name
  "close-quote": "close-quote"
  "col-resize": "col-resize"
  # "collapse": "collapse"
  "color-burn": "color-burn"
  "color-dodge": "color-dodge"
  "column-reverse": "column-reverse"
  # "condensed": "condensed"
  # "contain": "contain"
  "content-box": "content-box"
  "context-menu": "context-menu"
  # "copy": "copy"
  # "cover": "cover"
  # "crosshair": "crosshair"
  # "cursive": "cursive"
  "darken": "darken"
  "dashed": "dashed"
  # "decimal": "decimal"
  "decimal-leading-zero": "decimal-leading-zero"
  "difference": "difference"
  "disc": "disc"
  # "dot": "dot" # incompatible with the command "dot", use "keeper dot"
  "dotted": "dotted"
  # "double": "double"
  "double-circle": "double-circle"
  "east resize": "e-resize"
  "ease": "ease"
  "ease-in": "ease-in"
  "ease-in-out": "ease-in-out"
  "ease-out": "ease-out"
  # "edges": "edges"
  # "embed": "embed"
  "east west resize": "ew-resize"
  # "exclusion": "exclusion"
  "expanded": "expanded"
  "extra-condensed": "extra-condensed"
  "extra-expanded": "extra-expanded"
  "fantasy": "fantasy"
  # "fill": "fill"
  "filled": "filled"
  "fixed": "fixed"
  # "flat": "flat"
  "flex-end": "flex-end"
  "flex-start": "flex-start"
  "forwards": "forwards"
  "from-image": "from-image"
  "full-width": "full-width"
  "geometricPrecision": "geometricPrecision"
  # "georgian": "georgian"
  "grab": "grab"
  "grabbing": "grabbing"
  "groove": "groove"
  "hard-light": "hard-light"
  # "help": "help"
  "hidden": "hidden"
  # "hide": "hide"
  # "horizontal": "horizontal"
  "hue": "hue"
  # "infinite": "infinite"
  # "inherit": "inherit"
  # "initial": "initial"
  # "ink": "ink"
  "inline": "inline"
  "inline-block": "inline-block"
  "inline-flex": "inline-flex"
  "inline-grid": "inline-grid"
  "inline-table": "inline-table"
  # "inset": "inset" # incompatible with the function of the same name
  # "inside": "inside"
  # "invert": "invert"
  # "italic": "italic"
  # "justify": "justify"
  "keep-all": "keep-all"
  "lighten": "lighten"
  "lighter": "lighter"
  "line-through": "line-through"
  # "linear": "linear"
  "list-item": "list-item"
  "local": "local"
  "lower-alpha": "lower-alpha"
  "lower-greek": "lower-greek"
  "lower-latin": "lower-latin"
  "lower-roman": "lower-roman"
  # "lowercase": "lowercase"
  "left to right": "ltr"
  # "luminosity": "luminosity"
  # "manual": "manual"
  "margin-box": "margin-box"
  # "medium": "medium"
  # "middle": "middle"
  "monospace": "monospace"
  # "move": "move"
  # "multiply": "multiply"
  "north resize": "n-resize"
  "northeast resize": "ne-resize"
  "northeast southwest resize": "nesw-resize"
  "no-close-quote": "no-close-quote"
  "no-drop": "no-drop"
  "no-open-quote": "no-open-quote"
  "no-repeat": "no-repeat"
  "none": "none"
  # "normal": "normal"
  "not-allowed": "not-allowed"
  "nowrap": "nowrap"
  "north south resize": "ns-resize"
  "northwest resize": "nw-resize"
  "northwest southeast resize": "nwse-resize"
  # "objects": "objects"
  "oblique": "oblique"
  # "open": "open"
  "open-quote": "open-quote"
  "optimizeLegibility": "optimizeLegibility"
  "optimizeSpeed": "optimizeSpeed"
  "outset": "outset"
  # "outside": "outside"
  "outside-shape": "outside-shape"
  # "overlay": "overlay"
  # "overline": "overline"
  "padding-box": "padding-box"
  "painted": "painted"
  "paused": "paused"
  "petite-caps": "petite-caps"
  # "pointer": "pointer"
  "pre": "pre"
  "pre-line": "pre-line"
  "pre-wrap": "pre-wrap"
  "preserve-3d": "preserve-3d"
  # "progress": "progress"
  # "region": "region"
  # "relative": "relative"
  "repeat-x": "repeat-x"
  "repeat horizontal": "repeat-x"
  "repeat-y": "repeat-y"
  "repeat vertical": "repeat-y"
  # "reverse": "reverse"
  "ridge": "ridge"
  # "round": "round"
  "row": "row"
  "row-resize": "row-resize"
  "row-reverse": "row-reverse"
  "right to left": "rtl"
  "run-in": "run-in"
  # "running": "running"
  "south resize": "s-resize"
  "sans-serif": "sans-serif"
  # "saturation": "saturation"
  "scale-down": "scale-down"
  # "screen": "screen"
  # "scroll": "scroll"
  "southeast resize": "se-resize"
  "semi-condensed": "semi-condensed"
  "semi-expanded": "semi-expanded"
  # "separate": "separate"
  "serif": "serif"
  "sesame": "sesame"
  # "show": "show"
  "small-caps": "small-caps"
  "snap": "snap"
  "soft-light": "soft-light"
  # "solid": "solid"
  # "space": "space"
  "space-around": "space-around"
  "space-between": "space-between"
  # "spaces": "spaces"
  # "square": "square"
  # "static": "static"
  "step-end": "step-end"
  "step-start": "step-start"
  # "sticky": "sticky"
  # "stretch": "stretch"
  # "stroke": "stroke"
  # "style": "style"
  "sub": "sub"
  "super": "super"
  "southwest resize": "sw-resize"
  # "table": "table"
  "table-caption": "table-caption"
  "table-cell": "table-cell"
  "table-column": "table-column"
  "table-column-group": "table-column-group"
  "table-footer-group": "table-footer-group"
  "table-header-group": "table-header-group"
  "table-row": "table-row"
  "table-row-group": "table-row-group"
  # "text": "text"
  "text-bottom": "text-bottom"
  "text-top": "text-top"
  # "thick": "thick"
  # "thin": "thin"
  "titling-caps": "titling-caps"
  # "top": "top" # incompatible with the property of the same name
  "triangle": "triangle"
  "ultra-condensed": "ultra-condensed"
  "ultra-expanded": "ultra-expanded"
  # "underline": "underline"
  "unicase": "unicase"
  "unset": "unset"
  "upper-alpha": "upper-alpha"
  "upper-latin": "upper-latin"
  "upper-roman": "upper-roman"
  # "uppercase": "uppercase"
  # "vertical": "vertical"
  "vertical-text": "vertical-text"
  # "visible": "visible"
  "visibleFill": "visibleFill"
  "visiblePainted": "visiblePainted"
  "visibleStroke": "visibleStroke"
  "west resize": "w-resize"
  # "wait": "wait"
  # "wavy": "wavy"
  "weight": "weight"
  "wrap": "wrap"
  "wrap-reverse": "wrap-reverse"
  "zoom-in": "zoom-in"
  "zoom-out": "zoom-out"
# --------------------------------------------------
# fonts
# --------------------------------------------------
  "Abril  Fatface": "'Abril  Fatface'"
  "Aller": "'Aller'"
  "Amatic": "'Amatic'"
  "Andale Mono": "'Andale Mono'"
  "Anivers": "'Anivers'"
  "Arial": "Arial"
  "Aerial": "Arial"
  "Arielle": "Arial"
  "Arial Black": "'Arial Black'"
  "Arnoldboecklin": "Arnoldboecklin"
  "Arvo": "'Arvo'"
  "Audimat": "'Audimat'"
  "Avantgarde": "Avantgarde"
  "Blackout": "'Blackout'"
  "Blippo": "Blippo"
  "Book Antiqua": "'Book Antiqua'"
  "Bookman": "Bookman"
  "Brushstroke": "Brushstroke"
  "Cabin": "'Cabin'"
  "Charcoal": "Charcoal"
  "Chunk": "'Chunk'"
  "Comic Sans": "'Comic Sans'"
  "Comic Sans MS": "'Comic Sans MS'"
  "Coronetscript": "Coronetscript"
  "Courier New": "'Courier New'"
  "Delicious": "'Delicious'"
  "Droid Sans": "'Droid Sans'"
  "Fanwood": "'Fanwood'"
  "Fertigo Pro": "'Fertigo Pro'"
  "Florence": "Florence"
  "Fontin": "'Fontin'"
  "Fontaine": "'Fontin'"
  "Gadget": "Gadget"
  "Geneva": "Geneva"
  "Gill Sans": "'Gill Sans'"
  "Goudy Bookletter 1911": "'Goudy Bookletter 1911'"
  "Gaudy Bookletter 1911": "'Goudy Bookletter 1911'"
  "Helvetica": "Helvetica"
  "Helvetica Narrow": "'Helvetica Narrow'"
  "Helvetica Neue": "'Helvetica Neue'"
  "Helvetica New": "'Helvetica Neue'"
  "Impact": "Impact"
  "Josefin Slab": "'Josefin Slab'"
  "Junction": "'Junction'"
  "Knewave": "'Knewave'"
  "Lato": "'Lato'"
  "League Gothic": "'League Gothic'"
  "League Script Number One": "'League Script Number One'"
  "League Spartan": "'League Spartan'"
  "Linden Hill": "'Linden Hill'"
  "Lucida": "Lucida"
  "Lucida Console": "'Lucida Console'"
  "Lucida Grande": "'Lucida Grande'"
  "Lucida Sans Unicode": "'Lucida Sans Unicode'"
  "Lucidatypewriter": "Lucidatypewriter"
  "Monaco": "Monaco"
  "New Century Schoolbook": "'New Century Schoolbook'"
  "Old Standard TT": "'Old Standard TT'"
  "Old Standard": "'Old Standard TT'"
  "Oldtown": "Oldtown"
  "Open Sans": "'Open Sans'"
  "Orbitron": "'Orbitron'"
  "Ostrich Sans": "'Ostrich Sans'"
  "Pacifico": "'Pacifico'"
  "Palatino": "Palatino"
  "Palatino Linotype": "'Palatino Linotype'"
  "Parkavenue": "Parkavenue"
  "Playfair Display": "'Playfair Display'"
  "Prociono": "'Prociono'" # pro-tsee-O-no
  "PT Sans": "'PT Sans'"
  "Pity Sans": "'PT Sans'"
  "Raleway": "'Raleway'"
  "Roboto": "'Roboto'"
  "Seaside Resort": "'Seaside Resort'"
  "Sniglet": "'Sniglet'"
  "Sorts Mill Goudy": "'Sorts Mill Goudy'"
  "Source Sans Pro": "'Source Sans Pro'"
  "Tahoma": "Tahoma"
  "Times": "Times"
  "Times New Roman": "'Times New Roman'"
  "Trebuchet MS": "'Trebuchet MS'"
  "Ubuntu": "'Ubuntu'"
  "Verdana": "Verdana"
  "Vollkorn": "'Vollkorn'"
  "Zapf Chancery": "'Zapf Chancery'"
# --------------------------------------------------
# pseudo-classes
# --------------------------------------------------
  "active": ":active"
  "checked": ":checked"
  "default": ":default"
  "disabled": ":disabled"
  "empty": ":empty"
  "enabled": ":enabled"
  "first": ":first"
  "first child": ":first-child"
  "first of type": ":first-of-type"
  "focus": ":focus"
  "fullscreen": ":fullscreen"
  "hover": ":hover"
  "indeterminate": ":indeterminate"
  "in range": ":in-range"
  "invalid": ":invalid"
  "last child": ":last-child"
  "last of type": ":last-of-type"
  "pseudo-left": ":left"
  "link": ":link"
  "only child": ":only-child"
  "only of type": ":only-of-type"
  "optional": ":optional"
  "out of range": ":out-of-range"
  "read only": ":read-only"
  "read write": ":read-write"
  "required": ":required"
  "pseudo-right": ":right"
  "root": ":root"
  "route": ":root"
  "scope": ":scope"
  "target": ":target"
  "unresolved": ":unresolved"
  "valid": ":valid"
  "volleyed": ":valid"
  "visited": ":visited"
# --------------------------------------------------
# pseudo-elements
# --------------------------------------------------
  "after": "::after"
  "backdrop": "::backdrop"
  "before": "::before"
  "first letter": "::first-letter"
  "first line": "::first-line"
  "repeat index": "::repeat-index"
  "repeat item": "::repeat-item"
  "selection": "::selection"
# --------------------------------------------------
# at-rules
# --------------------------------------------------
  "charset": "@charset"
  "counter style": "@counter-style"
  "document": "@document"
  "font face": "@font-face"
  "font feature values": "@font-feature-values"
  "import": "@import"
  "keyframes": "@keyframes"
  "media": "@media"
  "namespace": "@namespace"
  "page": "@page"
  "supports": "@supports"
  "viewport": "@viewport"
# --------------------------------------------------
# functions
# --------------------------------------------------
  "directionality": ":dir()"
  "language": ":lang()"
  "not": ":not()"
  "nth child": ":nth-child()"
  "nth last child": ":nth-last-child()"
  "nth last of type": ":nth-last-of-type()"
  "nth of type": ":nth-of-type()"
  "annotation": "annotation()"
  "attribute": "attr()"
  "blur": "blur()"
  "brightness": "brightness()"
  "calculate": "calc()"
  "character variant": "character-variant()"
  "circle": "circle()"
  "contrast": "contrast()"
  "cubic bezier": "cubic-bezier()"
  "drop shadow": "drop-shadow()"
  "element": "element()"
  "ellipse": "ellipse()"
  "lips": "ellipse()" # If you use "ellipse" or "ellipsis" it doesn't work because those are commands
  "grayscale": "grayscale()"
  "hsl": "hsl()"
  "hassle": "hsl()"
  "hsla": "hsla()"
  "hassle alpha": "hsla()"
  "hue rotate": "hue-rotate()"
  "image": "image()"
  "inset": "inset()"
  "invert": "invert()"
  "linear gradient": "linear-gradient()"
  "matrix": "matrix()"
  "matrix3d": "matrix3d()"
  "minmax": "minmax()"
  "opacity fun": "opacity()" # To avoid ambiguity
  "ornaments": "ornaments()"
  "perspective fun": "perspective()" # use of 'fun' to avoid ambiguity with the perspective property
  "polygon": "polygon()"
  "radial gradient": "radial-gradient()"
  "rectangle": "rect()"
  "repeat": "repeat()"
  "repeating linear gradient": "repeating-linear-gradient()"
  "repeating radial gradient": "repeating-radial-gradient()"
  "rgb": "rgb()"
  "are to be": "rgb()"
  "rgba": "rgba()"
  "are to be a": "rgba()"
  "rotate": "rotate()"
  "rotatex": "rotatex()"
  "rotate horizontal": "rotatex()"
  "rotatey": "rotatey()"
  "rotate vertical": "rotatey()"
  "rotatez": "rotatez()"
  "rotate depth": "rotatez()"
  "rotate3d": "rotate3d()"
  "saturate": "saturate()"
  "scale": "scale()"
  "scalex": "scalex()"
  "scale horizontal": "scalex()"
  "scaley": "scaley()"
  "scale vertical": "scaley()"
  "scalez": "scalez()"
  "scale depth": "scalez()"
  "scale3d": "scale3d()"
  "sepia": "sepia()"
  "cpl": "sepia()"
  "skew": "skew()"
  "q": "skew()" # If you say "skew" the command "sku" gets called most of the time
  "skew horizontal": "skewx()"
  "q horizontal": "skewx()"
  "skew vertical": "skewy()"
  "q vertical": "skewy()"
  "steps": "steps()"
  "styleset": "styleset()"
  "stylistic": "stylistic()"
  "swash": "swash()" # Say "wash" to avoid confusion with the command "swash"
  "symbols fun": "symbols()" # use of 'fun' to avoid ambiguity with the symbols property
  "translate": "translate()"
  "translatex": "translatex()"
  "translate horizontal": "translatex()"
  "translatey": "translatey()"
  "translate vertical": "translatey()"
  "translatez": "translatez()"
  "translate depth": "translatez()"
  "translate3d": "translate3d()"
  "url": "url()"
  "var": "var()"
# --------------------------------------------------
# html elements
# --------------------------------------------------
  "a": "a"
  "abbreviation": "abbr"
  "address": "address"
  "area": "area"
  "article": "article"
  "aside": "aside"
  "audio": "audio"
  "b": "b"
  "bold": "b"
  "base": "base"
  "bidirectional isolation": "bdi"
  "bidirectional override": "bdo"
  "blockquote": "blockquote"
  "body": "body"
  "break": "br"
  "button": "button"
  "canvas": "canvas"
  "caption": "caption"
  "cite": "cite"
  "code": "code"
  "col": "col"
  "column": "col"
  "called": "col"
  "colgroup": "colgroup"
  "datalist": "datalist"
  "definition description": "dd"
  "del": "del"
  "d": "del"
  "deleted": "del"
  "details": "details"
  "define": "dfn"
  "dialog": "dialog"
  "div": "div"
  "division": "div"
  "divider": "div"
  "definition list": "dl"
  "definition term": "dt"
  "emphasis": "em"
  "embed": "embed"
  "fieldset": "fieldset"
  "figcaption": "figcaption"
  "figure": "figure"
  "footer": "footer"
  "form": "form"
  "heading 1": "h1"
  "heading 2": "h2"
  "heading to": "h2"
  "heading 3": "h3"
  "heading 4": "h4"
  "heading for": "h4"
  "heading 5": "h5"
  "heading 6": "h6"
  "head": "head"
  "header": "header"
  "horizontal rule": "hr"
  "html": "html"
  "i": "i"
  "italic": "i"
  "iframe": "iframe"
  "image": "img"
  "input": "input"
  "inserted": "ins"
  "keyboard": "kbd"
  "keygen": "keygen"
  "label": "label"
  "legend": "legend"
  "list item": "li"
  "link": "link"
  "main": "main"
  "map": "map"
  "mark": "mark"
  "menu": "menu"
  "menuitem": "menuitem"
  "meta": "meta"
  "meter": "meter"
  "navigation": "nav"
  "noscript": "noscript"
  "object": "object"
  "ol": "ol"
  "ordered list": "ol"
  "optgroup": "optgroup"
  "option": "option"
  "output": "output"
  "p": "p"
  "parameter": "param"
  "pre": "pre"
  "preformatted": "pre"
  "progress": "progress"
  "q": "q"
  "quotation": "q"
  "rp": "rp"
  "ruby p": "rp"
  "ruby paren": "rp"
  "ruby parenthesis": "rp"
  "ruby text": "rt"
  "rt": "rt"
  "ruby": "ruby"
  "s": "s"
  "sample": "samp"
  "script": "script"
  "section": "section"
  "select": "select"
  "small": "small"
  "source": "source"
  "span": "span"
  "strong": "strong"
  "style": "style"
  "sub": "sub"
  "subscript": "sub"
  "summary": "summary"
  "sup": "sup"
  "superscript": "sup"
  "table": "table"
  "tbody": "tbody"
  "table body": "tbody"
  "td": "td"
  "table data": "td"
  "table cell": "td"
  "textarea": "textarea"
  "tfoot": "tfoot"
  "table foot": "tfoot"
  "th": "th"
  "table header": "th"
  "thead": "thead"
  "table head": "thead"
  "time": "time"
  "title": "title"
  "table row": "tr"
  "tr": "tr"
  "track": "track"
  "u": "u"
  "ul": "ul"
  "unordered list": "ul"
  "var": "var"
  "variable": "var"
  "video": "video"
  "word break": "wbr"
